services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboard
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080